apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/abcall-frontend:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: LoadBalancer
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
