name: Build and Test Angular

# El workflow solo se ejecuta cuando se crea o actualiza un Pull Request
on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar el build del proyecto Angular
      - name: Build Angular project
        run: npm run build

      # 5. Ejecutar los tests unitarios con Karma
      - name: Run unit tests
        run: npm run test -- --watch=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'basingo-abcall'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Autenticar con Google Cloud usando la cuenta de servicio
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Authenticate to Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/abcall-frontend:latest .

      - name: Push Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/basingo-abcall/basinglo-abcall-misw/abcall-frontend:latest
